### PR TITLE
Update Test in README.rst to reflect API changes

### PR DESCRIPTION
**Pull request by naidoo88**
Including the target as the third argument in the cds.retrieve() method does not work with 0.7.2, returning the error:

AttributeError: 'str' object has no attribute 'download'

The included changes fix this issue, pointing the user to the appropriate syntax.

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf/cdsapi?pullRequest=119) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/cdsapi?pullRequest=119) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/cdsapi?pullRequest=119) it.</sub>

**Comment by naidoo88** [comment]
Realising the error was in the inclusion of `.download()`, inferred from inspecting the API request generated on the web order portal.  Removing this fixes the aforementioned issue, and as such the current documentation is correct!
